//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTools_Ultimate.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PatchNotes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PatchNotes() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eTools_Ultimate.Resources.PatchNotes", typeof(PatchNotes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {&quot;version&quot;:&quot;Test Scroll Version&quot;,&quot;date&quot;:&quot;2024-07-20&quot;,&quot;modifications&quot;:[{&quot;text&quot;:&quot;TEST: This entry is for testing the scroll function&quot;,&quot;type&quot;:0},{&quot;text&quot;:&quot;TEST: Another test entry to verify the scroll function&quot;,&quot;type&quot;:0},{&quot;text&quot;:&quot;TEST: Long text to test the text wrapping function in the scroll view. This text should be long enough to demonstrate and test the text wrapping function.&quot;,&quot;type&quot;:0},{&quot;text&quot;:&quot;TEST: Another long text entry to test the scroll function and the general user interface of the changelog dialo [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string TestScrollVersion {
            get {
                return ResourceManager.GetString("TestScrollVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {&quot;version&quot;:&quot;Version 1.0.0&quot;,&quot;date&quot;:&quot;2023-09-15&quot;,&quot;modifications&quot;:[{&quot;text&quot;:&quot;Initial release of eTools Ultimate&quot;,&quot;type&quot;:0},{&quot;text&quot;:&quot;Basic functionality for editing items&quot;,&quot;type&quot;:0},{&quot;text&quot;:&quot;Support for loading and saving Spec_Item.txt files&quot;,&quot;type&quot;:0},{&quot;text&quot;:&quot;Dark mode UI implemented&quot;,&quot;type&quot;:0}]}.
        /// </summary>
        internal static string Version_1_0_0 {
            get {
                return ResourceManager.GetString("Version_1_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {&quot;version&quot;:&quot;Version 1.2.0&quot;,&quot;date&quot;:&quot;2023-11-15&quot;,&quot;modifications&quot;:[{&quot;text&quot;:&quot;Added support for analyzing defineItem.h to extract item IDs&quot;,&quot;type&quot;:0},{&quot;text&quot;:&quot;Added support for analyzing mdlDyna.inc to obtain model filenames&quot;,&quot;type&quot;:0},{&quot;text&quot;:&quot;Reorganization of the General area with new field order&quot;,&quot;type&quot;:1},{&quot;text&quot;:&quot;Moved icon display from Visual Properties to the General area&quot;,&quot;type&quot;:1},{&quot;text&quot;:&quot;Improved image loading with support for DDS files&quot;,&quot;type&quot;:4},{&quot;text&quot;:&quot;Changed tradeable control to a modern toggle [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Version_1_2_0 {
            get {
                return ResourceManager.GetString("Version_1_2_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {&quot;version&quot;:&quot;Version 1.2.3&quot;,&quot;date&quot;:&quot;2024-06-20&quot;,&quot;modifications&quot;:[{&quot;text&quot;:&quot;Extended DDS texture preview with zoom controls&quot;,&quot;type&quot;:0},{&quot;text&quot;:&quot;Added detailed tooltips explaining DDS format options&quot;,&quot;type&quot;:0},{&quot;text&quot;:&quot;Improved transparency handling for DDS textures with pink backgrounds&quot;,&quot;type&quot;:4},{&quot;text&quot;:&quot;Implemented intelligent format detection for better DDS rendering&quot;,&quot;type&quot;:0},{&quot;text&quot;:&quot;Added pixel-perfect rendering for clearer icon display&quot;,&quot;type&quot;:4},{&quot;text&quot;:&quot;Consistent dark mode formatting across all dia [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Version_1_2_3 {
            get {
                return ResourceManager.GetString("Version_1_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {&quot;version&quot;:&quot;Version 1.2.4&quot;,&quot;date&quot;:&quot;2024-06-25&quot;,&quot;modifications&quot;:[{&quot;text&quot;:&quot;Completely redesigned DDS texture preview with extended zoom options (1x-10x)&quot;,&quot;type&quot;:4},{&quot;text&quot;:&quot;Optimized display of DDS textures with pixel-perfect scaling&quot;,&quot;type&quot;:4},{&quot;text&quot;:&quot;Dynamic size adjustment of the preview window based on zoom level and image content&quot;,&quot;type&quot;:0},{&quot;text&quot;:&quot;Improved dialog user interface with clearer arrangement and better accessibility&quot;,&quot;type&quot;:4},{&quot;text&quot;:&quot;Removed duplicate close buttons in the preview window&quot;, [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Version_1_2_4 {
            get {
                return ResourceManager.GetString("Version_1_2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {&quot;version&quot;:&quot;Version 1.2.5&quot;,&quot;date&quot;:&quot;2024-07-02&quot;,&quot;modifications&quot;:[{&quot;text&quot;:&quot;Converted table layout to a compact grid layout in the &apos;Collect&apos; tab&quot;,&quot;type&quot;:1},{&quot;text&quot;:&quot;Implemented SortableGridItem component for drag-and-drop functionality in grid format&quot;,&quot;type&quot;:0},{&quot;text&quot;:&quot;Optimized item display with two-column layout for better space efficiency&quot;,&quot;type&quot;:4},{&quot;text&quot;:&quot;Redesigned probability fields to display inline with element names&quot;,&quot;type&quot;:1},{&quot;text&quot;:&quot;Fixed data loading issues by passing availableItems directly th [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Version_1_2_5 {
            get {
                return ResourceManager.GetString("Version_1_2_5", resourceCulture);
            }
        }
    }
}
