//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTools_Ultimate.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PatchNotes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PatchNotes() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eTools_Ultimate.Resources.PatchNotes", typeof(PatchNotes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///  &quot;version&quot;: &quot;0.1.0 (Alpha)&quot;,
        ///  &quot;date&quot;: &quot;2025-10-02&quot;,
        ///  &quot;developerText&quot;: &quot;Welcome to the public Alpha of eTools Ultimate! This first version focuses on the main editors and a modern UI foundation. Expect rapid changes and frequent improvements as we collect your feedback.&quot;,
        ///  &quot;categories&quot;: {
        ///    &quot;added&quot;: [
        ///      {
        ///        &quot;text&quot;: &quot;Dashboard with quick navigation and localized interface&quot;,
        ///        &quot;type&quot;: 0
        ///      },
        ///      {
        ///        &quot;text&quot;: &quot;Editors: Movers, Motions, Giftboxes, Accessories, Texts&quot; [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Version_0_1_0 {
            get {
                return ResourceManager.GetString("Version_0_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///  &quot;version&quot;: &quot;0.1.1 (Alpha)&quot;,
        ///  &quot;date&quot;: &quot;2025-10-04&quot;,
        ///  &quot;developerText&quot;: &quot;This update introduces a new setting for custom file formats and includes a few bug fixes for smoother user experience. Florist files are now officially supported!&quot;,
        ///  &quot;categories&quot;: {
        ///    &quot;added&quot;: [
        ///      {
        ///        &quot;text&quot;: &quot;New setting: Files Format – allows specifying custom Flyff file structures (first supported: Florist files)&quot;,
        ///        &quot;type&quot;: 0
        ///      }
        ///    ],
        ///    &quot;changed&quot;: [],
        ///    &quot;improved&quot;: [],
        ///    &quot;fixed&quot;: [
        ///  [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Version_0_1_1 {
            get {
                return ResourceManager.GetString("Version_0_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///  &quot;version&quot;: &quot;0.2.0 (Alpha)&quot;,
        ///  &quot;date&quot;: &quot;2025-12-09&quot;,
        ///  &quot;developerText&quot;: &quot;This update introduces editing of mover drop lists, adds a tool to detect and remove unused assets, and includes several performance improvements along with various fixes.&quot;,
        ///  &quot;categories&quot;: {
        ///    &quot;added&quot;: [
        ///      {
        ///        &quot;text&quot;: &quot;New “Misc” page, allowing detection and removal of unused assets&quot;,
        ///        &quot;type&quot;: 0
        ///      },
        ///      {
        ///        &quot;text&quot;: &quot;Added a “Models Folder” setting in the configuration page&quot;,
        ///        &quot;type [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Version_0_2_0 {
            get {
                return ResourceManager.GetString("Version_0_2_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///  &quot;version&quot;: &quot;0.2.1 (Alpha)&quot;,
        ///  &quot;date&quot;: &quot;2025-12-15&quot;,
        ///  &quot;developerText&quot;: &quot;This update mainly focuses on bug fixes and stability improvements following the 0.2.0 release.&quot;,
        ///  &quot;categories&quot;: {
        ///    &quot;added&quot;: [
        ///      {
        ///        &quot;text&quot;: &quot;Added missing translations&quot;,
        ///        &quot;type&quot;: 0
        ///      }
        ///    ],
        ///    &quot;changed&quot;: [
        ///      {
        ///        &quot;text&quot;: &quot;Text entries in .txt files are now saved in alphabetical order based on their keys&quot;,
        ///        &quot;type&quot;: 1
        ///      }
        ///    ],
        ///    &quot;fixed&quot;: [
        ///      {
        ///        &quot;text&quot;:  [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Version_0_2_1 {
            get {
                return ResourceManager.GetString("Version_0_2_1", resourceCulture);
            }
        }
    }
}
