//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTools_Ultimate.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eTools_Ultimate.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mover O3D file.
        /// </summary>
        internal static string Mover3DFile {
            get {
                return ResourceManager.GetString("Mover3DFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the client folder.
        /// </summary>
        internal static string SelectClientFolder {
            get {
                return ResourceManager.GetString("SelectClientFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the icons folder.
        /// </summary>
        internal static string SelectIconsFolder {
            get {
                return ResourceManager.GetString("SelectIconsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the item icons folder.
        /// </summary>
        internal static string SelectItemIconsFolder {
            get {
                return ResourceManager.GetString("SelectItemIconsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the item prop file.
        /// </summary>
        internal static string SelectItemPropFile {
            get {
                return ResourceManager.GetString("SelectItemPropFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the item text file.
        /// </summary>
        internal static string SelectItemTextFile {
            get {
                return ResourceManager.GetString("SelectItemTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the model file associated to the mover.
        /// </summary>
        internal static string SelectMoverModelFile {
            get {
                return ResourceManager.GetString("SelectMoverModelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the mover prop ex file.
        /// </summary>
        internal static string SelectMoverPropExFile {
            get {
                return ResourceManager.GetString("SelectMoverPropExFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the mover prop file.
        /// </summary>
        internal static string SelectMoverPropFile {
            get {
                return ResourceManager.GetString("SelectMoverPropFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the mover text file.
        /// </summary>
        internal static string SelectMoverTextFile {
            get {
                return ResourceManager.GetString("SelectMoverTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the resources folder.
        /// </summary>
        internal static string SelectResourcesFolder {
            get {
                return ResourceManager.GetString("SelectResourcesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the skill icons folder.
        /// </summary>
        internal static string SelectSkillIconsFolder {
            get {
                return ResourceManager.GetString("SelectSkillIconsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the skill prop file.
        /// </summary>
        internal static string SelectSkillPropFile {
            get {
                return ResourceManager.GetString("SelectSkillPropFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the skill text file.
        /// </summary>
        internal static string SelectSkillTextFile {
            get {
                return ResourceManager.GetString("SelectSkillTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the sound configuration file.
        /// </summary>
        internal static string SelectSoundConfigFile {
            get {
                return ResourceManager.GetString("SelectSoundConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select a sound file.
        /// </summary>
        internal static string SelectSoundFile {
            get {
                return ResourceManager.GetString("SelectSoundFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the sounds folder.
        /// </summary>
        internal static string SelectSoundsFolder {
            get {
                return ResourceManager.GetString("SelectSoundsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the textures folder.
        /// </summary>
        internal static string SelectTexturesFolder {
            get {
                return ResourceManager.GetString("SelectTexturesFolder", resourceCulture);
            }
        }
    }
}
