//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTools_Ultimate.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eTools_Ultimate.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mover O3D file ähnelt.
        /// </summary>
        internal static string Mover3DFile {
            get {
                return ResourceManager.GetString("Mover3DFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the client folder ähnelt.
        /// </summary>
        internal static string SelectClientFolder {
            get {
                return ResourceManager.GetString("SelectClientFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the icons folder ähnelt.
        /// </summary>
        internal static string SelectIconsFolder {
            get {
                return ResourceManager.GetString("SelectIconsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the item icons folder ähnelt.
        /// </summary>
        internal static string SelectItemIconsFolder {
            get {
                return ResourceManager.GetString("SelectItemIconsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the item prop file ähnelt.
        /// </summary>
        internal static string SelectItemPropFile {
            get {
                return ResourceManager.GetString("SelectItemPropFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the item text file ähnelt.
        /// </summary>
        internal static string SelectItemTextFile {
            get {
                return ResourceManager.GetString("SelectItemTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the model file associated to the mover ähnelt.
        /// </summary>
        internal static string SelectMoverModelFile {
            get {
                return ResourceManager.GetString("SelectMoverModelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the mover prop ex file ähnelt.
        /// </summary>
        internal static string SelectMoverPropExFile {
            get {
                return ResourceManager.GetString("SelectMoverPropExFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the mover prop file ähnelt.
        /// </summary>
        internal static string SelectMoverPropFile {
            get {
                return ResourceManager.GetString("SelectMoverPropFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the mover text file ähnelt.
        /// </summary>
        internal static string SelectMoverTextFile {
            get {
                return ResourceManager.GetString("SelectMoverTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the resources folder ähnelt.
        /// </summary>
        internal static string SelectResourcesFolder {
            get {
                return ResourceManager.GetString("SelectResourcesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the skill icons folder ähnelt.
        /// </summary>
        internal static string SelectSkillIconsFolder {
            get {
                return ResourceManager.GetString("SelectSkillIconsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the skill prop file ähnelt.
        /// </summary>
        internal static string SelectSkillPropFile {
            get {
                return ResourceManager.GetString("SelectSkillPropFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the skill text file ähnelt.
        /// </summary>
        internal static string SelectSkillTextFile {
            get {
                return ResourceManager.GetString("SelectSkillTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the sound configuration file ähnelt.
        /// </summary>
        internal static string SelectSoundConfigFile {
            get {
                return ResourceManager.GetString("SelectSoundConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select a sound file ähnelt.
        /// </summary>
        internal static string SelectSoundFile {
            get {
                return ResourceManager.GetString("SelectSoundFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the sounds folder ähnelt.
        /// </summary>
        internal static string SelectSoundsFolder {
            get {
                return ResourceManager.GetString("SelectSoundsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the textures folder ähnelt.
        /// </summary>
        internal static string SelectTexturesFolder {
            get {
                return ResourceManager.GetString("SelectTexturesFolder", resourceCulture);
            }
        }
    }
}
