using eTools_Ultimate.Helpers;
using eTools_Ultimate.Models;
using Microsoft.Extensions.DependencyInjection;
using Scan;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace eTools_Ultimate.Services
{
    public class MotionsService(SettingsService settingsService, StringsService stringsService)
    {
        private readonly ObservableCollection<Motion> _motions = [];
        public ObservableCollection<Motion> Motions => this._motions;

        public string GetNextStringIdentifier()
        {
           return stringsService.GetNextStringIdentifier("IDS_PROPMOTION_TXT_");
        }

        private void ClearMotions()
        {
            foreach (Motion motion in this.Motions)
                motion.Dispose();
            this.Motions.Clear();
        }

        public void Load()
        {
            this.ClearMotions();

            using (Script script = new())
            {
                string filePath = settingsService.Settings.MotionsPropFilePath ?? settingsService.Settings.DefaultMotionsPropFilePath;
                script.Load(filePath);
                while (true)
                {
                    int nVer = script.GetNumber();

                    if (script.EndOfStream) break;

                    int dwId = script.GetNumber();
                    int dwMotion = script.GetNumber();
                    script.GetToken(); // ""
                    string szIconName = script.GetToken();
                    script.GetToken(); // ""
                    int dwPlay = script.GetNumber();
                    string szName = script.GetToken();
                    string szDesc = script.GetToken();

                    MotionProp prop = new(nVer, dwId, dwMotion, szIconName, dwPlay, szName, szDesc);
                    Motion motion = new(prop);
                    this.Motions.Add(motion);
                }
            }
        }

        public void Save()
        {
            Settings settings = App.Services.GetRequiredService<SettingsService>().Settings;

            string filePath = settings.MotionsPropFilePath ?? settings.DefaultMotionsPropFilePath;

            using StreamWriter writer = new(filePath, false, new UTF8Encoding(false));
            writer.WriteLine("// ========================================");
            writer.WriteLine("// Generated by eTools Ultimate");
            writer.WriteLine("// https://github.com/Maquinours/eTools");
            writer.WriteLine("// ========================================");
            writer.WriteLine();

            foreach (Motion motion in this.Motions)
            {
                MotionProp prop = motion.Prop;

                writer.Write(prop.NVer.ToString(CultureInfo.InvariantCulture));
                writer.Write('\t');
                writer.Write(motion.Identifier);
                writer.Write('\t');
                writer.Write(motion.MotionIdentifier);
                writer.Write('\t');
                writer.Write("\"\"\"");
                writer.Write(prop.SzIconName);
                writer.Write("\"\"\"");
                writer.Write('\t');
                writer.Write(prop.DwPlay.ToString(CultureInfo.InvariantCulture));
                writer.Write('\t');
                writer.Write(prop.SzName);
                writer.Write('\t');
                writer.Write(prop.SzDesc);
                writer.WriteLine();
            }
        }

        public Motion CreateMotion()
        {
            int dwId = (Motions.MaxBy(x => x.Prop.DwId)?.Prop.DwId ?? -1) + 1;

            string szName = GetNextStringIdentifier();
            stringsService.AddString(szName, "");
            string szDesc = GetNextStringIdentifier();
            stringsService.AddString(szDesc, "");

            MotionProp prop = new(nVer: settingsService.Settings.ResourcesVersion, dwId: dwId, dwMotion: 0, szIconName: "", dwPlay: 0, szName: szName, szDesc: szDesc);
            Motion motion = new(prop);

            Motions.Add(motion);

            return motion;
        }
    }
}
