using eTools_Ultimate.Helpers;
using eTools_Ultimate.Models;
using Scan;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace eTools_Ultimate.Services
{
    internal class MotionsService
    {
        private static readonly Lazy<MotionsService> _instance = new(() => new());
        public static MotionsService Instance => _instance.Value;

        private readonly ObservableCollection<Motion> _motions = [];
        public ObservableCollection<Motion> Motions => this._motions;

        private void ClearMotions()
        {
            foreach (Motion motion in this.Motions)
                motion.Dispose();
            this.Motions.Clear();
        }

        public void Load()
        {
            this.ClearMotions();

            Settings settings = Settings.Instance;

            using (Script script = new())
            {
                string filePath = settings.MotionsPropFilePath ?? settings.DefaultMotionsPropFilePath;
                script.Load(filePath);
                while (true)
                {
                    int nVer = script.GetNumber();

                    if (script.EndOfStream) break;

                    int dwId = script.GetNumber();
                    int dwMotion = script.GetNumber();
                    script.GetToken(); // ""
                    string szIconName = script.GetToken();
                    script.GetToken(); // ""
                    int dwPlay = script.GetNumber();
                    string szName = script.GetToken();
                    string szDesc = script.GetToken();

                    MotionProp prop = new(nVer, dwId, dwMotion, szIconName, dwPlay, szName, szDesc);
                    Motion motion = new(prop);
                    this.Motions.Add(motion);
                }
            }
        }

        public void Save()
        {
            Settings settings = Settings.Instance;

            string filePath = settings.MotionsPropFilePath ?? settings.DefaultMotionsPropFilePath;

            using StreamWriter writer = new(filePath, false, new UTF8Encoding(false));
            writer.WriteLine("// ========================================");
            writer.WriteLine("// Generated by eTools Ultimate");
            writer.WriteLine("// https://github.com/Maquinours/eTools");
            writer.WriteLine("// ========================================");

            foreach (Motion motion in this.Motions)
            {
                MotionProp prop = motion.Prop;

                writer.Write(prop.NVer.ToString(CultureInfo.InvariantCulture));
                writer.Write('\t');
                writer.Write(motion.Identifier);
                writer.Write('\t');
                writer.Write(motion.MotionIdentifier);
                writer.Write('\t');
                writer.Write("\"\"\"");
                writer.Write(prop.SzIconName);
                writer.Write("\"\"\"");
                writer.Write('\t');
                writer.Write(prop.DwPlay.ToString(CultureInfo.InvariantCulture));
                writer.Write('\t');
                writer.Write(prop.SzName);
                writer.Write('\t');
                writer.Write(prop.SzDesc);
                writer.WriteLine();
            }
        }
    }
}
