using eTools_Ultimate.Helpers;
using eTools_Ultimate.Models.Texts;
using Microsoft.Extensions.DependencyInjection;
using Scan;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace eTools_Ultimate.Services
{
    public class TextsService(SettingsService settingsService, StringsService stringsService)
    {
        private const string STRING_ID_PREFIX = "IDS_TEXTCLIENT_INC_";

        private readonly ObservableCollection<Text> _texts = [];
        public ObservableCollection<Text> Texts => this._texts;

        private void Clear()
        {
            foreach (Text text in this.Texts)
                text.Dispose();
            this.Texts.Clear();
        }

        public void Load()
        {
            this.Clear();

            string filePath = settingsService.Settings.TextsConfigFilePath ?? settingsService.Settings.DefaultTextsConfigFilePath;

            using (Script script = new())
            {
                script.Load(filePath);

                while (true)
                {
                    uint dwId = (uint)script.GetNumber();
                    if (script.EndOfStream) break;
                    
                    uint dwColor = (uint)script.GetNumber();
                    script.GetToken(); // "{"
                    string szName = script.GetToken();

                    // If the string is not in the strings service, then we generate a new key for it.
                    if (!stringsService.Strings.ContainsKey(szName))
                    {
                        string identifier = stringsService.GetNextStringIdentifier(STRING_ID_PREFIX);
                        stringsService.AddString(identifier, szName);
                        szName = identifier;
                    }

                    script.GetToken(); // "}"

                    Text text = new(dwId, dwColor, szName);

                    this.Texts.Add(text);
                }
            }
        }

        public void Save()
        {
            string filePath = settingsService.Settings.TextsConfigFilePath ?? settingsService.Settings.DefaultTextsConfigFilePath;

            using StreamWriter writer = new(filePath, false, new UTF8Encoding(false));

            writer.WriteLine("// ========================================");
            writer.WriteLine("// Generated by eTools Ultimate");
            writer.WriteLine("// https://github.com/Maquinours/eTools");
            writer.WriteLine("// ========================================");
            writer.WriteLine();

            foreach (Text text in Texts)
            {
                string hex = $"0x{text.DwColor:x8}";

                writer.Write(text.Identifier);
                writer.Write('\t');
                writer.Write(hex);
                writer.WriteLine();
                writer.WriteLine('{');
                writer.Write('\t');
                writer.Write(!stringsService.HasString(text.SzName) ? $"\"{text.SzName}\"" : text.SzName);
                writer.WriteLine();
                writer.WriteLine('}');
            }
        }

        public Text AddText()
        {
            uint dwId = Texts.MaxBy(x => x.DwId)?.DwId + 1 ?? 0;

            string szName = stringsService.GetNextStringIdentifier(STRING_ID_PREFIX);
            stringsService.GenerateNewString(szName);

            Text text = new(dwId: dwId, dwColor: 0xFFFFFFFF, szName: szName);

            this.Texts.Add(text);
            return text;
        }

        public void RemoveText(Text text)
        {
            text.Dispose();
            this.Texts.Remove(text);
        }
    }
}
